#import <UIKit/UIKit.h>
#import "BRGameLibrary.h"

NS_ASSUME_NONNULL_BEGIN

/// A 3-reel / 5-payline slot client. Results and EZ Coin accounting are
/// generated by the ez-slot-spin Edge Function, never by this controller.
@interface BRSlotMachineViewController : UIViewController

/// Adapts an existing Maze/Ricochet/community record as a Slot theme:
/// background→room, player→brain, enemy→7, obstacle→cherries. Any absent
/// image intentionally falls back to the built-in slot art.
- (instancetype)initWithBrainRotGameRecord:(BRGameRecord *)record;
@end

NS_ASSUME_NONNULL_END
