#import "BRSlotRoomViewController.h"
#import "EZAuthManager.h"
#import "EZSupabaseConfig.h"
#import <AVFoundation/AVFoundation.h>

@interface BRSlotRoomPromptController : UIViewController
@property (nonatomic, copy) NSString *promptTitle, *promptBody, *initialText;
@property (nonatomic, copy) NSArray<NSString *> *actions;
@property (nonatomic, copy) void (^selection)(NSInteger action, NSString *text);
@property (nonatomic, strong) UITextField *textField;
@end

@implementation BRSlotRoomPromptController
- (void)viewDidLoad { [super viewDidLoad]; self.view.backgroundColor = [UIColor colorWithRed:.055 green:.02 blue:.12 alpha:1]; self.modalPresentationStyle = UIModalPresentationPageSheet; self.sheetPresentationController.detents = @[[UISheetPresentationControllerDetent mediumDetent]]; self.sheetPresentationController.prefersGrabberVisible = YES; self.sheetPresentationController.preferredCornerRadius = 25;
    UIView *card = [UIView new]; card.backgroundColor = [UIColor colorWithRed:.13 green:.045 blue:.23 alpha:1]; card.layer.cornerRadius = 22; card.layer.borderWidth = 1; card.layer.borderColor = [UIColor colorWithRed:1 green:.75 blue:.18 alpha:.62].CGColor; card.translatesAutoresizingMaskIntoConstraints = NO; [self.view addSubview:card];
    UILabel *title = [UILabel new]; title.text = self.promptTitle; title.textColor = UIColor.whiteColor; title.font = [UIFont systemFontOfSize:24 weight:UIFontWeightBlack]; title.numberOfLines = 2; title.translatesAutoresizingMaskIntoConstraints = NO; [card addSubview:title];
    UILabel *body = [UILabel new]; body.text = self.promptBody; body.textColor = [UIColor colorWithWhite:.73 alpha:1]; body.font = [UIFont systemFontOfSize:14 weight:UIFontWeightMedium]; body.numberOfLines = 0; body.translatesAutoresizingMaskIntoConstraints = NO; [card addSubview:body];
    self.textField = [UITextField new]; self.textField.text = self.initialText; self.textField.placeholder = @"Display name"; self.textField.textColor = UIColor.whiteColor; self.textField.backgroundColor = [UIColor colorWithWhite:1 alpha:.09]; self.textField.layer.cornerRadius = 12; self.textField.leftView = [[UIView alloc] initWithFrame:CGRectMake(0,0,12,1)]; self.textField.leftViewMode = UITextFieldViewModeAlways; self.textField.translatesAutoresizingMaskIntoConstraints = NO; [card addSubview:self.textField]; self.textField.hidden = !self.initialText;
    UIStackView *buttons = [UIStackView new]; buttons.axis = UILayoutConstraintAxisVertical; buttons.spacing = 9; buttons.translatesAutoresizingMaskIntoConstraints = NO; [card addSubview:buttons]; [self.actions enumerateObjectsUsingBlock:^(NSString *name, NSUInteger index, BOOL *stop) { UIButton *b = [UIButton buttonWithType:UIButtonTypeSystem]; [b setTitle:name forState:UIControlStateNormal]; [b setTitleColor:index == self.actions.count - 1 ? [UIColor colorWithWhite:.72 alpha:1] : UIColor.whiteColor forState:UIControlStateNormal]; b.titleLabel.font = [UIFont systemFontOfSize:16 weight:UIFontWeightBlack]; b.backgroundColor = index == self.actions.count - 1 ? [UIColor colorWithWhite:1 alpha:.07] : [UIColor colorWithRed:.58 green:.12 blue:.42 alpha:1]; b.layer.cornerRadius = 12; b.tag = index; [b addTarget:self action:@selector(tapped:) forControlEvents:UIControlEventTouchUpInside]; [buttons addArrangedSubview:b]; [b.heightAnchor constraintEqualToConstant:43].active = YES; }];
    [NSLayoutConstraint activateConstraints:@[[card.leadingAnchor constraintEqualToAnchor:self.view.leadingAnchor constant:18], [card.trailingAnchor constraintEqualToAnchor:self.view.trailingAnchor constant:-18], [card.centerYAnchor constraintEqualToAnchor:self.view.centerYAnchor], [title.topAnchor constraintEqualToAnchor:card.topAnchor constant:22], [title.leadingAnchor constraintEqualToAnchor:card.leadingAnchor constant:20], [title.trailingAnchor constraintEqualToAnchor:card.trailingAnchor constant:-20], [body.topAnchor constraintEqualToAnchor:title.bottomAnchor constant:7], [body.leadingAnchor constraintEqualToAnchor:title.leadingAnchor], [body.trailingAnchor constraintEqualToAnchor:title.trailingAnchor], [self.textField.topAnchor constraintEqualToAnchor:body.bottomAnchor constant:16], [self.textField.leadingAnchor constraintEqualToAnchor:title.leadingAnchor], [self.textField.trailingAnchor constraintEqualToAnchor:title.trailingAnchor], [self.textField.heightAnchor constraintEqualToConstant:46], [buttons.topAnchor constraintEqualToAnchor:self.textField.hidden ? body.bottomAnchor : self.textField.bottomAnchor constant:18], [buttons.leadingAnchor constraintEqualToAnchor:title.leadingAnchor], [buttons.trailingAnchor constraintEqualToAnchor:title.trailingAnchor], [buttons.bottomAnchor constraintEqualToAnchor:card.bottomAnchor constant:-20]]]; }
- (void)tapped:(UIButton *)sender { NSString *text = self.textField.text ?: @""; NSInteger action = sender.tag; [self dismissViewControllerAnimated:YES completion:^{ if (self.selection) self.selection(action, text); }]; }
@end

@interface BRSlotRoomViewController () <UITableViewDataSource, UITableViewDelegate, UITextFieldDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate>
@property (nonatomic, copy) NSString *roomID;
@property (nonatomic, copy) NSString *roomTitle;
@property (nonatomic, strong) UITableView *table;
@property (nonatomic, strong) UITextField *composer;
@property (nonatomic, strong) UILabel *presenceLabel;
@property (nonatomic, strong) NSArray<NSDictionary *> *messages;
@property (nonatomic, strong) NSTimer *pollTimer;
@property (nonatomic) BOOL loading;
@property (nonatomic, strong) UIImage *pendingAvatar;
@property (nonatomic) BOOL musicEnabled;
@property (nonatomic, strong) AVAudioPlayer *loungeMusic;
@property (nonatomic, copy) NSString *profileName;
@end

@implementation BRSlotRoomViewController

- (instancetype)initWithRoomID:(NSString *)roomID title:(NSString *)title {
    if ((self = [super init])) { _roomID = [roomID copy]; _roomTitle = [title copy]; }
    return self;
}

- (void)viewDidLoad {
    [super viewDidLoad]; self.title = self.roomTitle; self.view.backgroundColor = [UIColor colorWithRed:.055 green:.02 blue:.12 alpha:1];
    self.navigationItem.rightBarButtonItem = [[UIBarButtonItem alloc] initWithImage:[UIImage systemImageNamed:@"person.crop.circle"] style:UIBarButtonItemStylePlain target:self action:@selector(editProfile)];
    self.navigationItem.rightBarButtonItem.tintColor = [UIColor colorWithRed:1 green:.78 blue:.22 alpha:1];
    self.presenceLabel = [UILabel new]; self.presenceLabel.text = @"● Connecting to lounge…"; self.presenceLabel.textAlignment = NSTextAlignmentCenter; self.presenceLabel.textColor = [UIColor colorWithRed:.55 green:1 blue:.72 alpha:1]; self.presenceLabel.font = [UIFont systemFontOfSize:13 weight:UIFontWeightBold]; self.presenceLabel.translatesAutoresizingMaskIntoConstraints = NO; [self.view addSubview:self.presenceLabel];
    self.table = [[UITableView alloc] initWithFrame:CGRectZero style:UITableViewStylePlain]; self.table.backgroundColor = UIColor.clearColor; self.table.separatorStyle = UITableViewCellSeparatorStyleNone; self.table.dataSource = self; self.table.delegate = self; self.table.keyboardDismissMode = UIScrollViewKeyboardDismissModeInteractive; self.table.translatesAutoresizingMaskIntoConstraints = NO; [self.view addSubview:self.table];
    UIView *bar = [UIView new]; bar.backgroundColor = [UIColor colorWithRed:.14 green:.055 blue:.24 alpha:1]; bar.layer.cornerRadius = 18; bar.translatesAutoresizingMaskIntoConstraints = NO; [self.view addSubview:bar];
    self.composer = [UITextField new]; self.composer.placeholder = @"Say something nice…"; self.composer.textColor = UIColor.whiteColor; self.composer.attributedPlaceholder = [[NSAttributedString alloc] initWithString:self.composer.placeholder attributes:@{NSForegroundColorAttributeName:[UIColor colorWithWhite:.62 alpha:1]}]; self.composer.delegate = self; self.composer.returnKeyType = UIReturnKeySend; self.composer.translatesAutoresizingMaskIntoConstraints = NO; [bar addSubview:self.composer];
    UIButton *send = [UIButton buttonWithType:UIButtonTypeSystem]; [send setImage:[UIImage systemImageNamed:@"paperplane.fill"] forState:UIControlStateNormal]; send.tintColor = [UIColor colorWithRed:1 green:.78 blue:.2 alpha:1]; send.titleLabel.font = [UIFont systemFontOfSize:18 weight:UIFontWeightBlack]; [send addTarget:self action:@selector(send) forControlEvents:UIControlEventTouchUpInside]; send.translatesAutoresizingMaskIntoConstraints = NO; [bar addSubview:send];
    UILabel *note = [UILabel new]; note.text = @"Be kind. Report messages by holding one. House hosts are characters, not players."; note.numberOfLines = 2; note.textAlignment = NSTextAlignmentCenter; note.font = [UIFont systemFontOfSize:11 weight:UIFontWeightMedium]; note.textColor = [UIColor colorWithWhite:.56 alpha:1]; note.translatesAutoresizingMaskIntoConstraints = NO; [self.view addSubview:note];
    UILayoutGuide *safe = self.view.safeAreaLayoutGuide;
    [NSLayoutConstraint activateConstraints:@[[self.presenceLabel.topAnchor constraintEqualToAnchor:safe.topAnchor constant:7], [self.presenceLabel.leadingAnchor constraintEqualToAnchor:safe.leadingAnchor constant:18], [self.presenceLabel.trailingAnchor constraintEqualToAnchor:safe.trailingAnchor constant:-18], [self.presenceLabel.heightAnchor constraintEqualToConstant:22], [self.table.topAnchor constraintEqualToAnchor:self.presenceLabel.bottomAnchor constant:3], [self.table.leadingAnchor constraintEqualToAnchor:safe.leadingAnchor constant:8], [self.table.trailingAnchor constraintEqualToAnchor:safe.trailingAnchor constant:-8], [self.table.bottomAnchor constraintEqualToAnchor:note.topAnchor constant:-4], [bar.leadingAnchor constraintEqualToAnchor:safe.leadingAnchor constant:14], [bar.trailingAnchor constraintEqualToAnchor:safe.trailingAnchor constant:-14], [bar.bottomAnchor constraintEqualToAnchor:safe.bottomAnchor constant:-8], [bar.heightAnchor constraintEqualToConstant:46], [self.composer.leadingAnchor constraintEqualToAnchor:bar.leadingAnchor constant:15], [self.composer.centerYAnchor constraintEqualToAnchor:bar.centerYAnchor], [self.composer.trailingAnchor constraintEqualToAnchor:send.leadingAnchor constant:-8], [send.trailingAnchor constraintEqualToAnchor:bar.trailingAnchor constant:-12], [send.centerYAnchor constraintEqualToAnchor:bar.centerYAnchor], [send.widthAnchor constraintEqualToConstant:34], [send.heightAnchor constraintEqualToConstant:34], [note.leadingAnchor constraintEqualToAnchor:safe.leadingAnchor constant:18], [note.trailingAnchor constraintEqualToAnchor:safe.trailingAnchor constant:-18], [note.bottomAnchor constraintEqualToAnchor:bar.topAnchor constant:-4], [note.heightAnchor constraintEqualToConstant:30]]];
    self.messages = @[]; [self refresh]; self.pollTimer = [NSTimer scheduledTimerWithTimeInterval:6 target:self selector:@selector(refresh) userInfo:nil repeats:YES];
}
- (void)viewWillDisappear:(BOOL)animated { [super viewWillDisappear:animated]; if (self.isMovingFromParentViewController || self.navigationController.isBeingDismissed) { [self.pollTimer invalidate]; [self.loungeMusic stop]; } }
- (void)dealloc { [self.pollTimer invalidate]; }

- (void)request:(NSDictionary *)body completion:(void (^)(NSDictionary *, NSString *))completion {
    [[EZAuthManager shared] getValidAccessToken:^(NSString *token, NSError *error) {
        if (!token.length) { if (completion) completion(nil, @"Sign in to join the lounge."); return; }
        NSURL *url = [NSURL URLWithString:[EZSupabaseURL stringByAppendingString:@"/functions/v1/br-slot-social"]]; NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:url]; request.HTTPMethod = @"POST"; request.timeoutInterval = 20; [request setValue:@"application/json" forHTTPHeaderField:@"Content-Type"]; [request setValue:[NSString stringWithFormat:@"Bearer %@", token] forHTTPHeaderField:@"Authorization"]; request.HTTPBody = [NSJSONSerialization dataWithJSONObject:body options:0 error:nil];
        [[[NSURLSession sharedSession] dataTaskWithRequest:request completionHandler:^(NSData *data, NSURLResponse *response, NSError *networkError) { NSDictionary *json = data ? [NSJSONSerialization JSONObjectWithData:data options:0 error:nil] : nil; NSString *message = networkError.localizedDescription ?: json[@"error"]; dispatch_async(dispatch_get_main_queue(), ^{ if (completion) completion(json, message); }); }] resume];
    }];
}
- (void)refresh { if (self.loading) return; self.loading = YES; [self request:@{ @"action": @"room_state", @"room_id": self.roomID } completion:^(NSDictionary *json, NSString *error) { self.loading = NO; if (error || !json) { self.presenceLabel.text = @"● Lounge reconnecting…"; self.presenceLabel.textColor = UIColor.systemOrangeColor; return; } NSDictionary *profile = [json[@"profile"] isKindOfClass:NSDictionary.class] ? json[@"profile"] : nil; self.profileName = [profile[@"display_name"] isKindOfClass:NSString.class] ? profile[@"display_name"] : nil; self.musicEnabled = [profile[@"music_enabled"] boolValue]; [self applyMusicPreference]; NSInteger active = [json[@"active_players"] integerValue]; self.presenceLabel.text = [NSString stringWithFormat:@"● %ld player%@ in the lounge", (long)active, active == 1 ? @"" : @"s"]; self.presenceLabel.textColor = [UIColor colorWithRed:.55 green:1 blue:.72 alpha:1]; self.messages = [json[@"messages"] isKindOfClass:NSArray.class] ? json[@"messages"] : @[]; [self.table reloadData]; if (self.messages.count) [self.table scrollToRowAtIndexPath:[NSIndexPath indexPathForRow:self.messages.count - 1 inSection:0] atScrollPosition:UITableViewScrollPositionBottom animated:NO]; if (!profile) [self offerProfileSetup]; }]; }
- (void)offerProfileSetup { static BOOL showing = NO; if (showing) return; showing = YES; BRSlotRoomPromptController *sheet = [BRSlotRoomPromptController new]; sheet.promptTitle = @"Join the lounge"; sheet.promptBody = @"Choose a public display name. Your email and account details stay private."; sheet.initialText = @""; sheet.actions = @[@"Save Profile", @"Not Now"]; sheet.selection = ^(NSInteger action, NSString *text) { showing = NO; if (action == 0) [self saveProfileName:text music:NO]; }; [self presentViewController:sheet animated:YES completion:nil]; }
- (void)editProfile { BRSlotRoomPromptController *sheet = [BRSlotRoomPromptController new]; sheet.promptTitle = @"Your lounge profile"; sheet.promptBody = @"Your profile is shown only in game lounges."; sheet.initialText = self.profileName ?: @""; sheet.actions = @[@"Choose Photo", self.musicEnabled ? @"Turn Music Off" : @"Play Lounge Music", @"Save Profile", @"Cancel"]; __weak typeof(self) weakSelf = self; sheet.selection = ^(NSInteger action, NSString *text) { __strong typeof(weakSelf) self = weakSelf; if (!self) return; NSString *name = text.length ? text : (self.profileName ?: @"Player"); if (action == 0) { UIImagePickerController *picker = [UIImagePickerController new]; picker.sourceType = UIImagePickerControllerSourceTypePhotoLibrary; picker.delegate = self; [self presentViewController:picker animated:YES completion:nil]; } else if (action == 1) { [self saveProfileName:name music:!self.musicEnabled]; } else if (action == 2) { [self saveProfileName:name music:self.musicEnabled]; } }; [self presentViewController:sheet animated:YES completion:nil]; }
- (void)imagePickerController:(UIImagePickerController *)picker didFinishPickingMediaWithInfo:(NSDictionary<UIImagePickerControllerInfoKey,id> *)info { self.pendingAvatar = info[UIImagePickerControllerOriginalImage]; [picker dismissViewControllerAnimated:YES completion:^{ [self editProfile]; }]; }
- (void)imagePickerControllerDidCancel:(UIImagePickerController *)picker { [picker dismissViewControllerAnimated:YES completion:nil]; }
- (void)saveProfileName:(NSString *)name music:(BOOL)music { if (name.length < 2) return; NSMutableDictionary *body = [@{ @"action": @"save_profile", @"display_name": name, @"music_enabled": @(music) } mutableCopy]; NSData *image = self.pendingAvatar ? UIImageJPEGRepresentation(self.pendingAvatar, .78) : nil; if (image.length) body[@"avatar_b64"] = [image base64EncodedStringWithOptions:0]; [self request:body completion:^(__unused NSDictionary *json, NSString *error) { if (!error) { self.pendingAvatar = nil; [self refresh]; } }]; }
- (void)applyMusicPreference { if (!self.musicEnabled) { [self.loungeMusic stop]; self.loungeMusic = nil; return; } if (self.loungeMusic.isPlaying) return; NSURL *url = [[NSBundle mainBundle] URLForResource:@"brainrot-theme1" withExtension:@"mp3"]; if (!url) url = [[NSBundle mainBundle] URLForResource:@"brainrot-theme1" withExtension:@"m4a"]; if (!url) return; self.loungeMusic = [[AVAudioPlayer alloc] initWithContentsOfURL:url error:nil]; self.loungeMusic.numberOfLoops = -1; self.loungeMusic.volume = .20; [self.loungeMusic play]; }
- (void)send { NSString *message = self.composer.text; if (!message.length) return; self.composer.text = @""; [self request:@{ @"action": @"send", @"room_id": self.roomID, @"message": message } completion:^(NSDictionary *json, NSString *error) { if (error) { self.composer.text = message; return; } [self refresh]; }]; }
- (BOOL)textFieldShouldReturn:(UITextField *)textField { [self send]; return NO; }
- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section { return self.messages.count + 1; }
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath { if (indexPath.row == 0) { UITableViewCell *cell = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:nil]; cell.backgroundColor = [UIColor colorWithRed:.30 green:.08 blue:.42 alpha:.55]; cell.textLabel.text = @"🎰 Cherry Queen · House host"; cell.textLabel.textColor = [UIColor colorWithRed:1 green:.79 blue:.25 alpha:1]; cell.textLabel.font = [UIFont systemFontOfSize:14 weight:UIFontWeightBlack]; cell.detailTextLabel.text = @"Welcome to the room! Spin responsibly and celebrate each other."; cell.detailTextLabel.textColor = [UIColor colorWithWhite:.78 alpha:1]; cell.detailTextLabel.numberOfLines = 0; return cell; } NSDictionary *message = self.messages[indexPath.row - 1]; UITableViewCell *cell = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:nil]; BOOL mine = [message[@"is_mine"] boolValue]; cell.backgroundColor = mine ? [UIColor colorWithRed:.22 green:.10 blue:.39 alpha:.65] : [UIColor colorWithWhite:1 alpha:.055]; cell.layer.cornerRadius = 12; cell.textLabel.text = message[@"display_name"] ?: @"Player"; cell.textLabel.textColor = mine ? [UIColor colorWithRed:1 green:.78 blue:.2 alpha:1] : UIColor.whiteColor; cell.textLabel.font = [UIFont systemFontOfSize:13 weight:UIFontWeightBlack]; cell.detailTextLabel.text = message[@"body"] ?: @""; cell.detailTextLabel.textColor = [UIColor colorWithWhite:.83 alpha:1]; cell.detailTextLabel.numberOfLines = 0; cell.imageView.image = [UIImage systemImageNamed:@"person.crop.circle.fill"]; cell.imageView.tintColor = [UIColor colorWithRed:1 green:.78 blue:.2 alpha:1]; cell.imageView.layer.cornerRadius = 17; cell.imageView.clipsToBounds = YES; NSString *avatarURL = [message[@"avatar_url"] isKindOfClass:NSString.class] ? message[@"avatar_url"] : nil; if (avatarURL.length) { NSURL *url = [NSURL URLWithString:avatarURL]; __weak UITableViewCell *weakCell = cell; [[[NSURLSession sharedSession] dataTaskWithURL:url completionHandler:^(NSData *data, NSURLResponse *response, NSError *error) { UIImage *image = data ? [UIImage imageWithData:data] : nil; if (!image) return; dispatch_async(dispatch_get_main_queue(), ^{ weakCell.imageView.image = image; weakCell.imageView.contentMode = UIViewContentModeScaleAspectFill; }); }] resume]; } return cell; }
- (CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath { return indexPath.row == 0 ? 62 : UITableViewAutomaticDimension; }
- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath { if (indexPath.row == 0 || [self.messages[indexPath.row - 1][@"is_mine"] boolValue]) return; NSDictionary *message = self.messages[indexPath.row - 1]; BRSlotRoomPromptController *sheet = [BRSlotRoomPromptController new]; sheet.promptTitle = @"Report this message?"; sheet.promptBody = @"Reports go to the room moderation queue. We won’t reveal who sent it."; sheet.actions = @[@"Report Message", @"Keep Browsing"]; __weak typeof(self) weakSelf = self; sheet.selection = ^(NSInteger action, NSString *text) { if (action == 0) [weakSelf request:@{ @"action": @"report", @"room_id": weakSelf.roomID, @"message_id": message[@"id"], @"reason": @"Player report" } completion:nil]; }; [self presentViewController:sheet animated:YES completion:nil]; }
@end
