#import "BRSlotGamePickerViewController.h"
#import "BRSlotMachineViewController.h"
#import "BRPennySlotViewController.h"
#import "BRGameLibrary.h"
#import "BRGamePickerViewController.h"

typedef NS_ENUM(NSInteger, BRSlotPickerCardKind) { BRSlotPickerCardKindClassic, BRSlotPickerCardKindPenny, BRSlotPickerCardKindCreate, BRSlotPickerCardKindCommunity, BRSlotPickerCardKindSaved };

@interface BRSlotPickerCard : UICollectionViewCell
- (void)configureWithTitle:(NSString *)title premise:(NSString *)premise image:(UIImage *)image kind:(BRSlotPickerCardKind)kind;
@end

@implementation BRSlotPickerCard { UIImageView *_art, *_fallbackIcon; UIView *_artFallback; UILabel *_titleLabel, *_premiseLabel; }
- (instancetype)initWithFrame:(CGRect)frame { self=[super initWithFrame:frame]; if (!self) return nil;
    self.contentView.backgroundColor=[UIColor colorWithWhite:1 alpha:.065]; self.contentView.layer.cornerRadius=19; self.contentView.layer.borderWidth=1; self.contentView.layer.borderColor=[[UIColor colorWithRed:1 green:.73 blue:.16 alpha:1] colorWithAlphaComponent:.36].CGColor; self.contentView.clipsToBounds=YES;
    _art=[UIImageView new]; _art.contentMode=UIViewContentModeScaleAspectFill; _art.clipsToBounds=YES; _art.translatesAutoresizingMaskIntoConstraints=NO; [self.contentView addSubview:_art];
    _artFallback=[UIView new]; _artFallback.translatesAutoresizingMaskIntoConstraints=NO; [self.contentView addSubview:_artFallback];
    _fallbackIcon=[UIImageView new]; _fallbackIcon.contentMode=UIViewContentModeScaleAspectFit; _fallbackIcon.translatesAutoresizingMaskIntoConstraints=NO; [_artFallback addSubview:_fallbackIcon];
    _titleLabel=[UILabel new]; _titleLabel.textColor=UIColor.whiteColor; _titleLabel.font=[UIFont systemFontOfSize:16 weight:UIFontWeightBlack]; _titleLabel.numberOfLines=2; _titleLabel.translatesAutoresizingMaskIntoConstraints=NO; [self.contentView addSubview:_titleLabel];
    _premiseLabel=[UILabel new]; _premiseLabel.textColor=[UIColor colorWithWhite:.70 alpha:1]; _premiseLabel.font=[UIFont systemFontOfSize:12 weight:UIFontWeightMedium]; _premiseLabel.numberOfLines=3; _premiseLabel.translatesAutoresizingMaskIntoConstraints=NO; [self.contentView addSubview:_premiseLabel];
    [NSLayoutConstraint activateConstraints:@[[_art.topAnchor constraintEqualToAnchor:self.contentView.topAnchor],[_art.leadingAnchor constraintEqualToAnchor:self.contentView.leadingAnchor],[_art.trailingAnchor constraintEqualToAnchor:self.contentView.trailingAnchor],[_art.heightAnchor constraintEqualToAnchor:self.contentView.heightAnchor multiplier:.53],[_artFallback.topAnchor constraintEqualToAnchor:_art.topAnchor],[_artFallback.leadingAnchor constraintEqualToAnchor:_art.leadingAnchor],[_artFallback.trailingAnchor constraintEqualToAnchor:_art.trailingAnchor],[_artFallback.bottomAnchor constraintEqualToAnchor:_art.bottomAnchor],[_fallbackIcon.centerXAnchor constraintEqualToAnchor:_artFallback.centerXAnchor],[_fallbackIcon.centerYAnchor constraintEqualToAnchor:_artFallback.centerYAnchor],[_fallbackIcon.widthAnchor constraintEqualToAnchor:_artFallback.heightAnchor multiplier:.52],[_fallbackIcon.heightAnchor constraintEqualToAnchor:_artFallback.heightAnchor multiplier:.52],[_titleLabel.topAnchor constraintEqualToAnchor:_art.bottomAnchor constant:10],[_titleLabel.leadingAnchor constraintEqualToAnchor:self.contentView.leadingAnchor constant:12],[_titleLabel.trailingAnchor constraintEqualToAnchor:self.contentView.trailingAnchor constant:-12],[_premiseLabel.topAnchor constraintEqualToAnchor:_titleLabel.bottomAnchor constant:4],[_premiseLabel.leadingAnchor constraintEqualToAnchor:_titleLabel.leadingAnchor],[_premiseLabel.trailingAnchor constraintEqualToAnchor:_titleLabel.trailingAnchor],[_premiseLabel.bottomAnchor constraintLessThanOrEqualToAnchor:self.contentView.bottomAnchor constant:-9]]]; return self; }
- (void)prepareForReuse { [super prepareForReuse]; _art.image=nil; _art.hidden=NO; _artFallback.hidden=NO; }
- (void)configureWithTitle:(NSString *)title premise:(NSString *)premise image:(UIImage *)image kind:(BRSlotPickerCardKind)kind { _titleLabel.text=title; _premiseLabel.text=premise; _art.image=image; _art.hidden=(image==nil); _artFallback.hidden=(image!=nil); UIColor *color=kind==BRSlotPickerCardKindPenny?[UIColor colorWithRed:.20 green:.36 blue:.24 alpha:1]:kind==BRSlotPickerCardKindCommunity?[UIColor colorWithRed:.23 green:.10 blue:.42 alpha:1]:kind==BRSlotPickerCardKindCreate?[UIColor colorWithRed:.05 green:.34 blue:.38 alpha:1]:[UIColor colorWithRed:.36 green:.10 blue:.42 alpha:1]; _artFallback.backgroundColor=color; NSString *symbol=kind==BRSlotPickerCardKindCommunity?@"person.3.fill":kind==BRSlotPickerCardKindCreate?@"paintpalette.fill":@"7.circle.fill"; _fallbackIcon.image=kind==BRSlotPickerCardKindPenny?[UIImage imageNamed:@"EZCoin"]:[UIImage systemImageNamed:symbol]; _fallbackIcon.tintColor=[UIColor colorWithRed:1 green:.78 blue:.18 alpha:1]; }
@end

@interface BRSlotGamePickerViewController () <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
@property (nonatomic,strong) UICollectionView *collectionView;
@property (nonatomic,strong) NSArray<BRGameRecord *> *importableGames;
@end

@implementation BRSlotGamePickerViewController
- (void)viewDidLoad { [super viewDidLoad]; self.title=@"Brainrot Slots"; self.view.backgroundColor=[UIColor colorWithRed:.04 green:.02 blue:.09 alpha:1]; self.navigationItem.leftBarButtonItem=[[UIBarButtonItem alloc] initWithCustomView:[self navigationButton]]; self.importableGames=BRGameLibrary.shared.allRecords;
    UILabel *header=[UILabel new]; header.text=@"SLOT GAMES"; header.font=[UIFont systemFontOfSize:28 weight:UIFontWeightBlack]; header.textColor=[UIColor colorWithRed:1 green:.78 blue:.18 alpha:1]; header.translatesAutoresizingMaskIntoConstraints=NO; [self.view addSubview:header];
    UILabel *detail=[UILabel new]; detail.text=@"Pick a machine, explore your saved worlds, or build a new slot room."; detail.textColor=[UIColor colorWithWhite:.68 alpha:1]; detail.font=[UIFont systemFontOfSize:14 weight:UIFontWeightMedium]; detail.numberOfLines=2; detail.translatesAutoresizingMaskIntoConstraints=NO; [self.view addSubview:detail];
    UICollectionViewFlowLayout *layout=[UICollectionViewFlowLayout new]; layout.minimumLineSpacing=13; layout.minimumInteritemSpacing=13; layout.sectionInset=UIEdgeInsetsMake(12,18,24,18); self.collectionView=[[UICollectionView alloc] initWithFrame:CGRectZero collectionViewLayout:layout]; self.collectionView.backgroundColor=UIColor.clearColor; self.collectionView.dataSource=self; self.collectionView.delegate=self; self.collectionView.alwaysBounceVertical=YES; self.collectionView.translatesAutoresizingMaskIntoConstraints=NO; [self.collectionView registerClass:BRSlotPickerCard.class forCellWithReuseIdentifier:@"SlotCard"]; [self.view addSubview:self.collectionView];
    [NSLayoutConstraint activateConstraints:@[[header.topAnchor constraintEqualToAnchor:self.view.safeAreaLayoutGuide.topAnchor constant:18],[header.leadingAnchor constraintEqualToAnchor:self.view.leadingAnchor constant:24],[header.trailingAnchor constraintEqualToAnchor:self.view.trailingAnchor constant:-24],[detail.topAnchor constraintEqualToAnchor:header.bottomAnchor constant:6],[detail.leadingAnchor constraintEqualToAnchor:header.leadingAnchor],[detail.trailingAnchor constraintEqualToAnchor:header.trailingAnchor],[self.collectionView.topAnchor constraintEqualToAnchor:detail.bottomAnchor constant:10],[self.collectionView.leadingAnchor constraintEqualToAnchor:self.view.leadingAnchor],[self.collectionView.trailingAnchor constraintEqualToAnchor:self.view.trailingAnchor],[self.collectionView.bottomAnchor constraintEqualToAnchor:self.view.bottomAnchor]]]; }
- (void)viewWillAppear:(BOOL)animated { [super viewWillAppear:animated]; self.importableGames=BRGameLibrary.shared.allRecords; [self.collectionView reloadData]; }
- (UIButton *)navigationButton { UIButton *button=[UIButton buttonWithType:UIButtonTypeSystem]; [button setTitle:@"‹  BRAINROT" forState:UIControlStateNormal]; button.titleLabel.font=[UIFont systemFontOfSize:12 weight:UIFontWeightBlack]; button.tintColor=[UIColor colorWithRed:1 green:.78 blue:.18 alpha:1]; button.backgroundColor=[UIColor colorWithRed:.13 green:.05 blue:.23 alpha:.96]; button.layer.cornerRadius=9; button.layer.borderWidth=1; button.layer.borderColor=[UIColor colorWithRed:1 green:.78 blue:.18 alpha:.72].CGColor; button.contentEdgeInsets=UIEdgeInsetsMake(7,10,7,10); [button sizeToFit]; [button addTarget:self action:@selector(close) forControlEvents:UIControlEventTouchUpInside]; return button; }
- (void)close { if (self.onReturnToBrainRotMenu) self.onReturnToBrainRotMenu(); else [self dismissViewControllerAnimated:YES completion:nil]; }
- (NSInteger)collectionView:(UICollectionView *)collectionView numberOfItemsInSection:(NSInteger)section { return 4+self.importableGames.count; }
- (BRSlotPickerCardKind)kindAtIndex:(NSInteger)index { return index<4 ? index : BRSlotPickerCardKindSaved; }
- (UICollectionViewCell *)collectionView:(UICollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)path { BRSlotPickerCard *cell=[collectionView dequeueReusableCellWithReuseIdentifier:@"SlotCard" forIndexPath:path]; BRSlotPickerCardKind kind=[self kindAtIndex:path.item]; if (kind==BRSlotPickerCardKindClassic) [cell configureWithTitle:@"Brainrot Slots" premise:@"The original three-reel room with five paylines and a progressive jackpot." image:nil kind:kind]; else if (kind==BRSlotPickerCardKindPenny) [cell configureWithTitle:@"EZCoin Penny Slots" premise:@"Five reels, nine lines, EZCoin scatters, and double-pay free spins." image:nil kind:kind]; else if (kind==BRSlotPickerCardKindCreate) [cell configureWithTitle:@"Create a Slot Room" premise:@"Build a custom world, background, and symbol set." image:nil kind:kind]; else if (kind==BRSlotPickerCardKindCommunity) [cell configureWithTitle:@"Browse Community" premise:@"Download other players’ rooms and use them as slot machines." image:nil kind:kind]; else { BRGameRecord *record=self.importableGames[path.item-4]; [cell configureWithTitle:record.themeTitle.length?record.themeTitle:@"Saved Slot Room" premise:record.premise.length?record.premise:@"Your saved Brainrot game is ready to play as a slot machine." image:record.backgroundImage kind:kind]; } return cell; }
- (CGSize)collectionView:(UICollectionView *)collectionView layout:(UICollectionViewLayout *)layout sizeForItemAtIndexPath:(NSIndexPath *)path { CGFloat width=floor((CGRectGetWidth(collectionView.bounds)-49)/2.0); return CGSizeMake(MAX(142,width),238); }
- (void)collectionView:(UICollectionView *)collectionView didSelectItemAtIndexPath:(NSIndexPath *)path { BRSlotPickerCardKind kind=[self kindAtIndex:path.item]; if (kind==BRSlotPickerCardKindPenny) { [self.navigationController pushViewController:[BRPennySlotViewController new] animated:YES]; return; } if (kind==BRSlotPickerCardKindCommunity) { BRGamePickerViewController *community=[BRGamePickerViewController new]; community.startsOnCommunityTab=YES; __weak typeof(self) weakSelf=self; community.onSlotThemeSelection=^(BRGameRecord *record) { __strong typeof(weakSelf) self=weakSelf; if (self) [self.navigationController pushViewController:[[BRSlotMachineViewController alloc] initWithBrainRotGameRecord:record] animated:YES]; }; community.modalPresentationStyle=UIModalPresentationFullScreen; [self presentViewController:community animated:YES completion:nil]; return; } BRSlotMachineViewController *slots=kind==BRSlotPickerCardKindSaved?[[BRSlotMachineViewController alloc] initWithBrainRotGameRecord:self.importableGames[path.item-4]]:[BRSlotMachineViewController new]; if (kind==BRSlotPickerCardKindCreate) slots.title=@"New Slot Game"; [self.navigationController pushViewController:slots animated:YES]; }
@end
